# Generated by Django 4.1.4 on 2022-12-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhps_main_app', '0002_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='upload_cv',
            field=models.FileField(upload_to='cv/'),
        ),
    ]
