# Generated by Django 4.1.4 on 2023-01-05 00:54

from django.db import migrations, models
import jhps_main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jhps_main_app', '0003_alter_applyjob_upload_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='select_page',
            field=models.IntegerField(choices=[(0, 'Class Room Learning'), (1, 'E-Learning'), (2, 'Curriculum Syllabus')]),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='upload_cv',
            field=models.FileField(upload_to='cv/', validators=[jhps_main_app.validators.validate_file_size]),
        ),
    ]
