# Generated by Django 4.1.4 on 2023-01-21 04:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jhps_main_app', '0004_alter_academics_select_page_alter_applyjob_upload_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_enquiry',
            name='academic_year',
            field=models.IntegerField(blank=True, choices=[(0, '2022-23'), (1, '2023-24')], null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='father_designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='father_income',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='father_mobile_No',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='father_orgnization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='local_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Local'), (1, 'Non-Local')], null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='mobile_No',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='relation',
            field=models.IntegerField(blank=True, choices=[(0, 'FATHER'), (1, 'MOTHER')], null=True),
        ),
    ]
