# Generated by Django 4.1.4 on 2023-01-24 14:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jhps_main_app', '0005_alter_student_enquiry_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='C1_DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='C2_DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='F_DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='Last_Worked',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='M_DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='Present_Salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='Sp_DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='father_mobile_No',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='mobile_No',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='mother_mobile_No',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='student_enquiry',
            name='reference_mobile_No',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, null=True, region=None),
        ),
    ]
