# Generated by Django 4.1.4 on 2023-01-24 14:40

from django.db import migrations, models
import jhps_main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jhps_main_app', '0006_alter_applyjob_c1_dob_alter_applyjob_c2_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/', validators=[jhps_main_app.validators.validate_file_size]),
        ),
    ]
