# Generated by Django 4.1.4 on 2023-03-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jhps_main_app', '0007_alter_applyjob_upload_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
