# Generated by Django 4.1.4 on 2023-03-03 06:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jhps_main_app', '0008_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('paragraph_data', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('upload_image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EventsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_image', models.FileField(upload_to='events_images/')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jhps_main_app.events')),
            ],
        ),
    ]
