# Generated by Django 4.1.4 on 2023-03-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jhps_main_app', '0009_events_eventsimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventsImage',
            new_name='EventImages',
        ),
    ]
