# Generated by Django 4.1.4 on 2023-03-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jhps_main_app', '0010_rename_eventsimage_eventimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice_Board',
        ),
    ]
